version: 2.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      # Docker image with Go pre-installed to make hugo install easier
      - image: cimg/go:1.15.6

    steps:
      - checkout

      - run:
          name: Update apt-get
          command: sudo apt-get update

      - run:
          name: Install hugo
          command: sudo apt-get install hugo

      - run:
          name: Install hugo theme
          command: git submodule update --init

      - run:
          # TODO: include --buildDrafts?
          name: Build site
          command: hugo

      - store_artifacts:
          path: public/
